#!/usr/bin/env bash

set -Eeuo pipefail

checksum() {
  sha1sum - < <({
    cat "$1"
    echo "$2"
  }) | cut -f 1 -d ' '
}

tmp="$(mktemp)"
file="$HOME/.mache/$(checksum "$@")"

{
  mkdir -p ~/.mache &> /dev/null
  tail -n +2 "$1" > "$tmp"
  chmod u=rx "$tmp"
}

#(>&2 printf "mache: %s %s %s\n" "$1" "$2" "$file")
test -f "$file" || {
  touch "$file"
  ($tmp > "$file" && chmod -w "$file") || {
    >&2 printf "mache: failed\n"
    rm "$file"
    exit 1
  }
}

cat "$file"
rm -f "$tmp"
